#GENERAL INFORMATION
STUDENT_NAME: Name
REFRESH_RATE: 500 #milliseconds
NETWORK:
  SSID: wifi
  PASSWORD: password
NEO_PIXEL:
  RGB: TRUE
    RED: 100
    GREEN: 20
    BLUE: 30
    BRIGHTNESS: 10
  HSV: FALSE
    HUE: 40
    SATURATION: 50
    VALUE: 50

#UNITS
UNITS:
  ALTITUDE:
    FEET:       FALSE
    METERS:     TRUE
  PRESSURE:
    PASCAL:     FALSE
    MBAR:       TRUE
    K_PASCAL:   FALSE
    IN_HG:      FALSE
    MM_HG:      FALSE
    PSI:        FALSE
  TEMPERATURE:
    CELSIUS:    TRUE
    FAHRENHEIT: FALSE

#SENSOR SELECTION
SENSORS:
  ENS160:   FALSE
  LPS22:    TRUE
  LTR390:   FALSE
  MAX17048: FALSE
  SCD40:    FALSE
  SHT41:    FALSE
  VEML7700: FALSE