M48
; DRILL file {KiCad 7.0.11} date Tue Mar 26 20:33:31 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-03-26T20:33:31-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.540
%
G90
G05
T1
X121.06Y-98.552
X127.89Y-98.552
T2
X162.56Y-99.06
X162.56Y-116.84
M30
